---
- name: Встановлення Fail2ban
  apt:
    name: fail2ban
    state: present

- name: Розгортання конфігурації Fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: "0644"
  notify: restart fail2ban

- name: Запуск та увімкнення Fail2ban
  systemd:
    name: fail2ban
    enabled: yes
    state: started
