---
- name: Налаштування VM1 — Командний сервер
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    svc_user: "svcuser"
    node_exporter_port: 9101

  roles:
    - role: "{{ playbook_dir }}/../roles/common"
    - role: "{{ playbook_dir }}/../roles/nginx"
    - role: "{{ playbook_dir }}/../roles/fail2ban"
    - role: "{{ playbook_dir }}/../roles/node_exporter"
