---
- name: Налаштування VM2 — Сервер моніторингу
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    svc_user: "svcuser"
    node_exporter_port: 9101
    prometheus_port: 9090
    grafana_port: 3000
    vm1_ip: "192.168.177.18"

  roles:
    - role: "{{ playbook_dir }}/../roles/common"
    - role: "{{ playbook_dir }}/../roles/fail2ban"
    - role: "{{ playbook_dir }}/../roles/prometheus"
    - role: "{{ playbook_dir }}/../roles/grafana"
