---
- name: Налаштування VM2 — Сервер моніторингу
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    svc_user: "svcuser"
    node_exporter_port: 9101
    prometheus_port: 9090
    grafana_port: 3000
    vm1_ip: "192.168.177.18"

  roles:
    - role: /home/falcon/diploma/ansible/roles/common
    - role: /home/falcon/diploma/ansible/roles/fail2ban
    - role: /home/falcon/diploma/ansible/roles/prometheus
    - role: /home/falcon/diploma/ansible/roles/grafana
